coverage:
  status:
    project:
      default:
        target: 50%    # the required coverage value
        threshold: 10%  # the leniency in hitting the target
        informational: true
    patch:
      default:
        informational: true

